name: continuous diployement

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: |   
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
      - run: npm run deploy
     
