name: continuous diployement

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build App
        run: | 
              npm install
              npm run build
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
           target_branch: gh-pages
           build_dir: build
        env:
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}    
